#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to create
# and install the OCNE OCI-CCM  module.
#
# If you want to encrypt this file, please execute following command:
#
#  $ cp deploy-mod-ociccm-example.yml deploy-mod-ociccm.yml
#  $ <edit your settings in var-section>
#  $ ansible-vault encrypt deploy-mod-ociccm.yml
#
# yamllint disable

---

- name: Setting the OCI-CM Health Check Network Ports
  hosts: ocne_kube_worker ocne_new_kube_worker
  become: yes
  gather_facts: false

  tasks:

  - name: Open Port 10256 TCP
    firewalld:
      port: 10256/tcp
      permanent: yes
      state: enabled

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
      enabled: yes


- name: Create and Deploy an OCI-CCM Module
  hosts: ocne_op
  gather_facts: false

  vars:
    oci_region: "<enter oci region here>"
    oci_tenancy: "<enter tenancy id here>"
    oci_compartment: "<enter compartment id here>"
    oci_user: "<enter oci_user id  here>"
    oci_fingerprint: "<enter your fingerprint here>"
    oci_private_key: /tmp/oci_api_key.pem
    oci_vcn: "<enter oci vcn id for ocne servers here>"
    oci_lb_subnet1: "<enter oci subnet for loadbalancer here>"

  tasks:

  - name: Copy the Oracle Cloud Infrastructure API signing key
    copy:
      src: "{{ playbook_dir }}/files/oci_api_key.pem"
      dest: "{{oci_private_key}}"
      mode: 0600

  - name: Create an Oracle OCI-CCM Module
    command: olcnectl module create \
        --environment-name {{ ocne_environment }} \
        --module oci-ccm \
        --name {{ ocne_oci }} \
        --oci-ccm-helm-module {{ ocne_helm }} \
        --oci-region {{ oci_region }} \
        --oci-tenancy {{ oci_tenancy }} \
        --oci-user {{ oci_user }} \
        --oci-fingerprint {{ oci_fingerprint }} \
        --oci-vcn {{ oci_vcn }} \
        --oci-lb-subnet1 {{ oci_lb_subnet1 }} \
        --oci-compartment {{ oci_compartment }} \
        --oci-private-key {{ oci_private_key }} 

  - name: Validate the Oracle OCI-CCM Module
    command: olcnectl module validate \
        --environment-name {{ ocne_environment }} \
        --name {{ ocne_oci }}

  - name: Deploy the Oracle OCI-CCM Module
    command: olcnectl module install \
        --environment-name {{ ocne_environment }} \
        --name {{ ocne_oci }}
    register: deploy_oci_ccm
    until: deploy_oci_ccm is not failed
    retries: 3
