- name: Known exploit detection
  hosts: all

  tasks: 
      - name: Installing ksplice-known-exploit-detection pacakge
        package:
          name: ksplice-known-exploit-detection
          state: present

      - name: Editing /etc/uptrack/uptrack.conf
        shell: grep -q "^enabled = yes$" /etc/uptrack/uptrack.conf || echo -e "[Known-Exploit-Detection]\nenabled = yes" >> /etc/uptrack/uptrack.conf
     
      - name: Activating the feature.
        shell: uptrack-upgrade -y 

      - name: Scan /var/log/messages for attempts
        shell: "grep -E '\\<CVE-[0-9]{4}-[0-9]{4,7}\\>' /var/log/messages| wc -l"
        register: exploit_count
        ignore_errors: yes
      
     

      - name: Print count to output
        debug:
         msg: "Detected {{ exploit_count.stdout }} attempts to breach the system"
        when: exploit_count.stdout|int > 0
      
      - name: Print details
        shell: "grep -E '\\<CVE-[0-9]{4}-[0-9]{4,7}\\>' /var/log/messages"
        register: cve_msgs
        ignore_errors: yes

      - debug:
         msg: "{{ cve_msgs.stdout_lines }}"
