---
#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to create a VM using Oracle Linux Virtualization Manager (OLVM)
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# A password file is needed which contains the passwords for the local OLVM Manager as well as the root user for the VM.
# The password file is encrypted using the ansible-vault command. Once encrypted I created a Vault credential using this file.
# The template for OLAM needs the Vault credential as well as the local user credential.
# Within the lab OLAM server I placed the file in: /var/lib/awx/projects/files with awx:awx permissions for both file and directory.
# The files is declared below in the vars_files reference.
# The vars section contains the OLVM FQDN, user and VM / Template details which should be edited to support your local environment.
# Details below are examples from within our lab environment.

- hosts: all
  become: yes
  vars_files:
    - /var/lib/awx/projects/files/ovirt_passwords.yaml
  
  vars:
    olvm_fqdn: ovirt.it.oracle.com
    olvm_user: shayler@internal
    olvm_cafile: /etc/pki/ovirt-engine/ca.pem
    olvm_cluster: cluster03
    olvm_template: OL8U5_x86_64-olvm-b107_nov21_NODE03
    vm_ram: 2048MiB
    vm_dns: 192.168.100.2
    vm_dns_domain: example.com
    vm_gateway: 192.168.100.1
    vm_netmask: 255.255.255.0
    vm_timezone: Europe/London
    vm_hostname: vm01.example.com
    vm_ip_address: 192.168.100.41
    vm_name: SimonVM1
    
  tasks:
    - name: Login to OLVM manager
      ovirt_auth:
        hostname: "{{ olvm_fqdn }}"
        username: "{{ olvm_user }}"
        password: "{{ olvm_password }}"
        ca_file: "{{ olvm_cafile | default(omit) }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Create and run VM from template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_name }}"
        template: "{{ olvm_template }}"
        cluster: "{{ olvm_cluster }}"
        memory: "{{ vm_ram }}"
        high_availability: true
        state: running
        wait: yes
        cloud_init:
          host_name: "{{ vm_hostname }}"
          user_name: root
          root_password: "{{ vm_root_passwd }}"
          dns_servers: "{{ vm_dns }}"
          dns_search: "{{ vm_dns_domain }}"
          nic_name: "{{ vm_nicname | default('eth0') }}"
          nic_on_boot: true
          nic_boot_protocol: static
          nic_ip_address: "{{ vm_ip_address }}"
          nic_gateway: "{{ vm_gateway }}"
          nic_netmask: "{{ vm_netmask }}"
          timezone: "{{ vm_timezone }}"
          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ vm_hostname }}
              - yum -y remove cloud-init

    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
