environments:
    - environment-name: ocne_env
      globals:
        api-server: ocne-operator.example.com:8091
      modules:
        - module: kubernetes
          name: ocne_cluster
          generate-scripts: true
          args:
            container-registry: container-registry-ams.oracle.com/olcne
            virtual-ip: 192.168.178.81
            master-nodes: 
                - ocne-control01.example.com:8090
                - ocne-control02.example.com:8090
                - ocne-control03.example.com:8090
            worker-nodes:
                - ocne-worker01.example.com:8090
                - ocne-worker02.example.com:8090
                - ocne-worker03.example.com:8090
                - ocne-worker04.example.com:8090
            selinux: enforcing
            restrict-service-externalip: false
        - module: helm 
          name: myhelm 
          args:
            helm-kubernetes-module: ocne_cluster
