#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to install & start HTTPD and configure an iptables based firewall
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

---
- hosts: all
  become: yes
  tasks:
  - name: Initialise aide
    command: aide --init
  - name: Enable Database for aide
    command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
